- name: Add the DataStax repository key
  apt_key: url=http://debian.datastax.com/debian/repo_key

- name: Add the DataStax Community repository
  apt_repository: repo='deb http://debian.datastax.com/community stable main' update_cache=yes

- name: install opscenter agent
  apt: name=datastax-agent
  
- name: put address.yaml
  template: src=address.yaml dest=/var/lib/datastax-agent/conf/address.yaml
  register: opscenter_agent_conf

- name: start or restart opscenter agent
  service: name=datastax-agent enabled=yes state={{ 'restarted' if opscenter_agent_conf.changed else 'started' }}